### ISSUE TITLE
Heartbeat it's binary sensor

### ISSUE THREAD

**Issue by krom** [TheTinkerDad/sensible#10]
I have the few proposals for this sensor

1. Replace `sensor` with `binary_sensor` with

```json
{
  "device_class": "connectivity",
  "entity_categiry": "diagnostic"
}
```

2. Send offliene before disconnection, you can handle SIGTERM handler

3. Use [SetWill](https://github.com/eclipse/paho.mqtt.golang/blob/v1.4.2/options.go#L298) for automatic offline feature
4. Use one topic for availability and heartbeat sensor

**Comment by TheTinkerDad** [comment]
Thank you for the suggestion! This is something I'm still playing with although it's lower priority compared to other missing or in progress features. My original goes for the heartbeat sensor was to have a way to trigger an automation if the server/container/etc. goes down and I successfully used it with Node Red for example.

My biggest problem with things like SetWill is that according to my experience they still won't trigger if a container suddenly crashes, although I have to admit I haven't done enough testing to for a 100% sure conclusion!

**Comment by krom** [comment]
I used the `will` feature with node-red and it's works fine for me. It trigged on network disconnection, power failure and service shutdown.

**Comment by TheTinkerDad** [comment]
This weekend I'm working on Sensible and right now I'm in the process of implementing your suggestion. Truth to be hold, I realized that in the past I've used the whole "will" feature wrong, because of a bad misconception I had in my head about how this works... Oh well! :)

This will soon be added to the "latest" branch along with a lot of improvements and bugfixes.

**Comment by TheTinkerDad** [comment]
![image](https://user-images.githubusercontent.com/6706631/234138919-593d4abe-5c84-4a5f-8b81-558fca8b523f.png)
Well, this is what I've ended up with - no need for the Heartbeat NR sensor and the need to simulate the last will using NodeRED - this just works. :) However I couldn't set the device class to connectivity as doing so - for whatever reason - turned the sensor invisible in HA.
