### ISSUE TITLE
Didn't create settings or log file.

### ISSUE THREAD

**Issue by ScrewLooseDan** [TheTinkerDad/sensible#3]
Tried following your examples to run this on Ubuntu 22.04.2 LTS.  Tried running the binary from the releases (didn't build).

root@host:/opt/sensible# /opt/sensible/sensible 
2023/03/19 21:15:30 Opening configuration file...
2023/03/19 21:15:30 Config file not found, writing default config...
2023/03/19 21:15:30 <nil>

The program would just exit.

I manually created the settings file with just mqtt, discovery, and the heartbeat plugin.  That got me:

root@host:/opt/sensible# /opt/sensible/sensible 
2023/03/19 21:27:35 Opening configuration file...
2023/03/19 21:27:35 Connecting to MQTT broker at 127.0.0.1:1883...
2023/03/19 21:27:35 Error opening file: open /var/log/sensible/sensible.log: no such file or directory
2023/03/19 21:27:35 Connected

And again, the program just quit.

I made the /var/log/sensible directory and touched the file sensible.log, and presto!  It appears to work.

Not a big deal to manually make those files, but when your quick start section implies that would be created I figured I would let you know.

**Comment by TheTinkerDad** [comment]
Sorry, this is clearly a bug. The next release will try to create those folders on its own and print out an error message if it fails to do so.

**Comment by TheTinkerDad** [comment]
This should now be fixed on the https://github.com/TheTinkerDad/sensible/tree/latest branch.
