### ISSUE TITLE
Command line help

### ISSUE THREAD

**Issue by ggee** [TheTinkerDad/sensible#5]
Some basic command line help.  At least a --version option to know what we are running.

**Comment by TheTinkerDad** [comment]
Good idea for the future, thank you, although Sensible currently doesn't have any command line parameters.

On the other hand, adding the version number to be printed out is a must indeed.

**Comment by TheTinkerDad** [comment]
This is now implemented on the https://github.com/TheTinkerDad/sensible/tree/latest branch.
